# RENAME FILE TO 'config.yml'
bot:
  token: MTMwOTIwMzkyNDk1MTEwOTcyNA.GbwqPR.NHVdW5NtcZiCZjmZ-z7poQZOq_M4EPV5D0cexc
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 
  bonus_cooldown: 12 
