# RENAME FILE TO 'config.yml'
bot:
  token: DISCORD_TOKEN
  owner_ids:
    - 1310345940116177071
    - 1309194929930633279
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 
  bonus_cooldown: 12 
